//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryFog.NameParser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryFog.NameParser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de
        ///van
        ///van der
        ///van het.
        /// </summary>
        internal static string DutchLastNamesPrefixes {
            get {
                return ResourceManager.GetString("DutchLastNamesPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma
        ///Olivia
        ///Sophia
        ///Isabella
        ///Ava
        ///Mia
        ///Emily
        ///Abigail
        ///Madison
        ///Charlotte
        ///Harper
        ///Sofia
        ///Avery
        ///Elizabeth
        ///Amelia
        ///Evelyn
        ///Ella
        ///Chloe
        ///Victoria
        ///Aubrey
        ///Grace
        ///Zoey
        ///Natalie
        ///Addison
        ///Lillian
        ///Brooklyn
        ///Lily
        ///Hannah
        ///Layla
        ///Scarlett
        ///Aria
        ///Zoe
        ///Samantha
        ///Anna
        ///Leah
        ///Audrey
        ///Ariana
        ///Allison
        ///Savannah
        ///Arianna
        ///Camila
        ///Penelope
        ///Gabriella
        ///Claire
        ///Aaliyah
        ///Sadie
        ///Riley
        ///Skylar
        ///Nora
        ///Sarah
        ///Hailey
        ///Kaylee
        ///Paisley
        ///Kennedy
        ///Ellie
        ///Peyton
        ///Annabelle
        ///Caroline
        ///Madelyn
        ///Serenity
        ///Aubree
        ///Lucy
        ///Alexa
        ///Alexi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleFirstNames {
            get {
                return ResourceManager.GetString("FemaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts receivable.
        /// </summary>
        internal static string JobTitles {
            get {
                return ResourceManager.GetString("JobTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noah
        ///Liam
        ///Mason
        ///Jacob
        ///William
        ///Ethan
        ///Michael
        ///Alexander
        ///James
        ///Daniel
        ///Elijah
        ///Benjamin
        ///Logan
        ///Aiden
        ///Jayden
        ///Matthew
        ///Jackson
        ///David
        ///Lucas
        ///Joseph
        ///Anthony
        ///Andrew
        ///Samuel
        ///Gabriel
        ///Joshua
        ///John
        ///Carter
        ///Luke
        ///Dylan
        ///Christopher
        ///Isaac
        ///Oliver
        ///Henry
        ///Sebastian
        ///Caleb
        ///Owen
        ///Ryan
        ///Nathan
        ///Wyatt
        ///Hunter
        ///Jack
        ///Christian
        ///Landon
        ///Jonathan
        ///Levi
        ///Jaxon
        ///Julian
        ///Isaiah
        ///Eli
        ///Aaron
        ///Charles
        ///Connor
        ///Cameron
        ///Thomas
        ///Jordan
        ///Jeremiah
        ///Nicholas
        ///Evan
        ///Adrian
        ///Gavin
        ///Robert
        ///Brayden
        ///Grayson
        ///Josiah
        ///Colto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleFirstNames {
            get {
                return ResourceManager.GetString("MaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de
        ///dela
        ///de la.
        /// </summary>
        internal static string SpanishLastNamesPrefixes {
            get {
                return ResourceManager.GetString("SpanishLastNamesPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///BROWN
        ///JONES
        ///MILLER
        ///DAVIS
        ///GARCIA
        ///RODRIGUEZ
        ///WILSON
        ///MARTINEZ
        ///ANDERSON
        ///TAYLOR
        ///THOMAS
        ///HERNANDEZ
        ///MOORE
        ///MARTIN
        ///JACKSON
        ///THOMPSON
        ///WHITE
        ///LOPEZ
        ///LEE
        ///GONZALEZ
        ///HARRIS
        ///CLARK
        ///LEWIS
        ///ROBINSON
        ///WALKER
        ///PEREZ
        ///HALL
        ///YOUNG
        ///ALLEN
        ///SANCHEZ
        ///WRIGHT
        ///KING
        ///SCOTT
        ///GREEN
        ///BAKER
        ///ADAMS
        ///NELSON
        ///HILL
        ///RAMIREZ
        ///CAMPBELL
        ///MITCHELL
        ///ROBERTS
        ///CARTER
        ///PHILLIPS
        ///EVANS
        ///TURNER
        ///TORRES
        ///PARKER
        ///COLLINS
        ///EDWARDS
        ///STEWART
        ///FLORES
        ///MORRIS
        ///NGUYEN
        ///MURPHY
        ///RIVERA
        ///COOK
        ///ROGERS
        ///MORGAN
        ///PETERSON
        ///CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USCensusLastNames {
            get {
                return ResourceManager.GetString("USCensusLastNames", resourceCulture);
            }
        }
    }
}
