//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace BinaryFog.NameParser {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new ResourceManager("BinaryFog.NameParser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co
        ///company
        ///ltd
        ///llc
        ///limited
        ///inc
        ///incorperated
        ///corp
        ///corporation.
        /// </summary>
        internal static string CompanySuffixes {
            get {
                return ResourceManager.GetString("CompanySuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma
        ///Olivia
        ///Sophia
        ///Isabella
        ///Ava
        ///Mia
        ///Emily
        ///Abigail
        ///Madison
        ///Charlotte
        ///Harper
        ///Sofia
        ///Avery
        ///Elizabeth
        ///Amelia
        ///Evelyn
        ///Ella
        ///Chloe
        ///Victoria
        ///Aubrey
        ///Grace
        ///Zoey
        ///Natalie
        ///Addison
        ///Lillian
        ///Brooklyn
        ///Lily
        ///Hannah
        ///Layla
        ///Scarlett
        ///Aria
        ///Zoe
        ///Samantha
        ///Anna
        ///Leah
        ///Audrey
        ///Ariana
        ///Allison
        ///Savannah
        ///Arianna
        ///Camila
        ///Penelope
        ///Gabriella
        ///Claire
        ///Aaliyah
        ///Sadie
        ///Riley
        ///Skylar
        ///Nora
        ///Sarah
        ///Hailey
        ///Kaylee
        ///Paisley
        ///Kennedy
        ///Ellie
        ///Peyton
        ///Annabelle
        ///Caroline
        ///Madelyn
        ///Serenity
        ///Aubree
        ///Lucy
        ///Alexa
        ///Alexi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleFirstNames {
            get {
                return ResourceManager.GetString("FemaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bchd
        ///bd
        ///bds
        ///bdsc
        ///bohdsc
        ///dc
        ///dcm
        ///dd
        ///dds
        ///ddsc
        ///dmd
        ///dmsc
        ///do
        ///dpm
        ///dpt
        ///dvm
        ///esq
        ///fcps
        ///jd
        ///kbe
        ///md
        ///mds
        ///mdsc
        ///mhl
        ///mmsc
        ///ms
        ///msc
        ///mscds
        ///msd
        ///od
        ///phd
        ///scd
        ///vmd.
        /// </summary>
        internal static string HonorificTitles {
            get {
                return ResourceManager.GetString("HonorificTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts receivable
        ///senator
        ///doctor
        ///president
        ///vice president.
        /// </summary>
        internal static string JobTitles {
            get {
                return ResourceManager.GetString("JobTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de
        ///van
        ///van der
        ///van het
        ///de
        ///dela
        ///de la.
        /// </summary>
        internal static string LastNamePrefixes {
            get {
                return ResourceManager.GetString("LastNamePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noah
        ///Liam
        ///Mason
        ///Jacob
        ///William
        ///Ethan
        ///Michael
        ///Alexander
        ///James
        ///Daniel
        ///Elijah
        ///Benjamin
        ///Logan
        ///Aiden
        ///Jayden
        ///Matthew
        ///Jackson
        ///David
        ///Lucas
        ///Joseph
        ///Anthony
        ///Andrew
        ///Samuel
        ///Gabriel
        ///Joshua
        ///John
        ///Carter
        ///Luke
        ///Dylan
        ///Christopher
        ///Isaac
        ///Oliver
        ///Henry
        ///Sebastian
        ///Caleb
        ///Owen
        ///Ryan
        ///Nathan
        ///Wyatt
        ///Hunter
        ///Jack
        ///Christian
        ///Landon
        ///Jonathan
        ///Levi
        ///Jaxon
        ///Julian
        ///Isaiah
        ///Eli
        ///Aaron
        ///Charles
        ///Connor
        ///Cameron
        ///Thomas
        ///Jordan
        ///Jeremiah
        ///Nicholas
        ///Evan
        ///Adrian
        ///Gavin
        ///Robert
        ///Brayden
        ///Grayson
        ///Josiah
        ///Colto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleFirstNames {
            get {
                return ResourceManager.GetString("MaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i
        ///ii
        ///iii
        ///iv
        ///v
        ///vi
        ///vii
        ///viii
        ///ix
        ///x
        ///xi
        ///xii
        ///xiii
        ///xiv
        ///xv
        ///xvi
        ///xvii
        ///xviii
        ///xix
        ///jr
        ///sr.
        /// </summary>
        internal static string Suffixes {
            get {
                return ResourceManager.GetString("Suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr
        ///ms
        ///mrs
        ///dr.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///BROWN
        ///JONES
        ///MILLER
        ///DAVIS
        ///GARCIA
        ///RODRIGUEZ
        ///WILSON
        ///MARTINEZ
        ///ANDERSON
        ///TAYLOR
        ///THOMAS
        ///HERNANDEZ
        ///MOORE
        ///MARTIN
        ///JACKSON
        ///THOMPSON
        ///WHITE
        ///LOPEZ
        ///LEE
        ///GONZALEZ
        ///HARRIS
        ///CLARK
        ///LEWIS
        ///ROBINSON
        ///WALKER
        ///PEREZ
        ///HALL
        ///YOUNG
        ///ALLEN
        ///SANCHEZ
        ///WRIGHT
        ///KING
        ///SCOTT
        ///GREEN
        ///BAKER
        ///ADAMS
        ///NELSON
        ///HILL
        ///RAMIREZ
        ///CAMPBELL
        ///MITCHELL
        ///ROBERTS
        ///CARTER
        ///PHILLIPS
        ///EVANS
        ///TURNER
        ///TORRES
        ///PARKER
        ///COLLINS
        ///EDWARDS
        ///STEWART
        ///FLORES
        ///MORRIS
        ///NGUYEN
        ///MURPHY
        ///RIVERA
        ///COOK
        ///ROGERS
        ///MORGAN
        ///PETERSON
        ///CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USCensusLastNames {
            get {
                return ResourceManager.GetString("USCensusLastNames", resourceCulture);
            }
        }
    }
}
